_target_: deepcryspy.job_handlers.task_handlers.ComputationHandler
hardware_interface:
  _target_: deepcryspy.job_handlers.SlurmInterface
executable: ${globals.executable}
script: compute_reference_labels.py
slurm_args:
  job-name: ref_sp
  partition: cpu-2h
  gpus-per-node: 0
  ntasks-per-node: ${reference_computation.n_processes}
  time: 0-02:00:00
calculator_inputs: ${reference_computation.calculator_inputs}
kspacing: ${reference_computation.kspacing}
pseudopotentials: ${reference_computation.pseudopotentials}
pwx_path: ${reference_computation.pwx_path}
n_threads: ${reference_computation.n_threads}
n_processes: ${reference_computation.n_processes}
results_db_path: ${paths.train_db}
state_path: state_reference_computation.yaml
